### ISSUE TITLE
New version of VCRedist (14.32) available with Visual Studio 2022 17.2

### ISSUE THREAD

**Issue by Thieum** [aaronparker/vcredist#104]
# Expected Behavior

I would like to have access to the latest available  version of VCRedist that was made available with the release of Visual Studio 2022 17.2.

This latest version is the one provided here : https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

The exact version is : 14.32.31326.0

It is also available through my.visualstudio.com and listed as  Visual C++ Redistributable for Visual Studio 2022 (version 17.2)

![image](https://user-images.githubusercontent.com/944894/172927756-d5f01a61-bdcd-428a-a0fe-d6fc0331185d.png)

# Current Behavior

The version is not available yet in the supported versions.

# Failure Information (for bugs)

N/A - new feature.

## Steps to Reproduce

N/A - new feature.

## Context

N/A - new feature.

## Failure Logs

N/A - new feature.

**Comment by aaronparker** [comment]
I'm not sure I understand the request. That is the version that's available in VcRedist:

```powershell
PS /Users/aaron/projects/vcredist> Get-VcList -Release 2022

Name            : Visual C++ Redistributable for Visual Studio 2022
ProductCode     : {2d507699-404c-4c8b-a54a-38e352f32cdd}
Version         : 14.32.31326.0
URL             : https://www.visualstudio.com/downloads/
Download        : https://aka.ms/vs/17/release/VC_redist.x64.exe
Release         : 2022
Architecture    : x64
Install         : /install /passive /norestart
SilentInstall   : /install /quiet /norestart
SilentUninstall : "%ProgramData%\Package Cache\{2d507699-404c-4c8b-a54a-38e352f32cdd}\VC_redist.x64.exe" /uninstall /quiet /noreboot
UninstallKey    : 32

Name            : Visual C++ Redistributable for Visual Studio 2022
ProductCode     : {817e21c1-6b3a-4bc1-8c49-67e4e1887b3a}
Version         : 14.32.31326.0
URL             : https://www.visualstudio.com/downloads/
Download        : https://aka.ms/vs/17/release/VC_redist.x86.exe
Release         : 2022
Architecture    : x86
Install         : /install /passive /norestart
SilentInstall   : /install /quiet /norestart
SilentUninstall : "%ProgramData%\Package Cache\{817e21c1-6b3a-4bc1-8c49-67e4e1887b3a}\VC_redist.x86.exe" /uninstall /quiet /noreboot
UninstallKey    : 32
```

**Comment by Thieum** [comment]
ah indeed, nevermind! I based my request on the doc page here: https://vcredist.com/versions/#why

**Comment by aaronparker** [comment]
Ah OK. That docs page should be automatically updated. I'll look to fix that.

**Comment by aaronparker** [comment]
[https://vcredist.com/versions/](https://vcredist.com/versions/) should now list the current versions.
