### ISSUE TITLE
Get-VCList -Release 2022 returns not the newest Version

### ISSUE THREAD

**Issue by KurtTheBerner** [aaronparker/vcredist#108]
# Expected Behavior

Please describe the behavior you are expecting.
`Get-VCList `should return the correct (newest available) Version of Release 2022

# Current Behavior

What is the current behavior?
`Get-VCList` returns actually the Version 14.32.31326.0 of Release 2022, which is not the newest. It should return 14.32.31332.0
`Get-VcList | Save-VcRedist -Path $downloadDir | Out-Null`  Downloads the correct (newest) Version of Release 2022

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug by issuing the command using the `-Verbose` command.

```
Paste the verbose output from the command here
VERBOSE: Get-VcList: Reading JSON document [C:\Users\xxxx\Documents\PowerShell\Modules\VcRedist\3.0.336\VisualCRedistributables.json].
VERBOSE: Get-VcList: Converting JSON.
VERBOSE: Get-VcList: Object count is: 2.

Name            : Visual C++ Redistributable for Visual Studio 2022
ProductCode     : {2d507699-404c-4c8b-a54a-38e352f32cdd}
Version         : 14.32.31326.0
URL             : https://www.visualstudio.com/downloads/
Download        : https://aka.ms/vs/17/release/VC_redist.x64.exe
Release         : 2022
Architecture    : x64
Install         : /install /passive /norestart
SilentInstall   : /install /quiet /norestart
SilentUninstall : "%ProgramData%\Package Cache\{2d507699-404c-4c8b-a54a-38e352f32cdd}\VC_redist.x64.exe" /uninstall
                  /quiet /noreboot
UninstallKey    : 32

Name            : Visual C++ Redistributable for Visual Studio 2022
ProductCode     : {817e21c1-6b3a-4bc1-8c49-67e4e1887b3a}
Version         : 14.32.31326.0
URL             : https://www.visualstudio.com/downloads/
Download        : https://aka.ms/vs/17/release/VC_redist.x86.exe
Release         : 2022
Architecture    : x86
Install         : /install /passive /norestart
SilentInstall   : /install /quiet /norestart
SilentUninstall : "%ProgramData%\Package Cache\{817e21c1-6b3a-4bc1-8c49-67e4e1887b3a}\VC_redist.x86.exe" /uninstall
                  /quiet /noreboot
UninstallKey    : 32
```

**_If it is not a bug, please remove the rest of this template._**

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Step
Get-VcList -Release 2022

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* **VcRedist Version**: Use `Get-Module -ListAvailable VcRedist` 
3.0.336
* **PowerShell Version**: Use `Get-PSVersion` 
7.2.5
* **Operating System**: Windows
10.0.19044.1766

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by aaronparker** [comment]
Fixed in #109
