### ISSUE TITLE
URLs for downloading certain Visual C++ 2005/2008 Redistributables lead to 404

### ISSUE THREAD

**Issue by thabse** [aaronparker/vcredist#114]
# Expected Behavior

When saving a Redistributable with Version 9.0.21022.218 or 9.0.21022, it should be downloaded. Example:
```
Get-VcList -Export Unsupported | Where-Object { $_.Architecture -eq "x86" -and $_.Version -eq "9.0.21022.218"} | Save-VcRedist -Path C:\temp\VcRedist
```

# Current Behavior

The file is not downloaded as it's unavailable (404).

# Failure Information (for bugs)

```
Get-VcList -Export Unsupported | Where-Object { $_.Architecture -eq "x86" -and $_.Version -eq "9.0.21022.218"} | Save-VcRedist -Path C:\temp\VcRedist -Verbose
WARNING: Get-VcList: This list includes unsupported Visual C++ Redistributables.
VERBOSE: Save-VcRedist: Test folder: [C:\temp\VcRedist\2008\9.0.21022.218\x86].
VERBOSE: Save-VcRedist: Folder [C:\temp\VcRedist\2008\9.0.21022.218\x86] exists. Skipping.
VERBOSE: Save-VcRedist: Testing target: C:\temp\VcRedist\2008\9.0.21022.218\x86\vcredist_x86.exe
VERBOSE: Performing the operation "Invoke-WebRequest" on target
"https://download.microsoft.com/download/d/1/0/d10d210e-e0ad-4010-b547-bc5e395ef691/vcredist_x86.exe".
VERBOSE: Save-VcRedist: Download VcRedist: [2008, x86, 9.0.21022.218]
VERBOSE: GET with 0-byte payload
WARNING: Save-VcRedist: Failed to download: [Visual C++ 2008 Feature Pack Redistributable Package].
WARNING: Save-VcRedist: URL: [https://download.microsoft.com/download/d/1/0/d10d210e-e0ad-4010-b547-bc5e395ef691/vcredist_x86.exe].
WARNING: Save-VcRedist: Download failed with: [The remote server returned an error: (404) Not Found.]
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run `Get-VcList -Export Unsupported | Where-Object { $_.Architecture -eq "x86" -and $_.Version -eq "9.0.21022.218"} | Save-VcRedist -Path C:\temp\VcRedist`

Note: I did not check if any other Versions are affected as well.

**Comment by aaronparker** [comment]
The download pages, such as [https://www.microsoft.com/en-us/download/details.aspx?id=18471](https://www.microsoft.com/en-us/download/details.aspx?id=18471), no longer exist, so I can only assume that Microsoft may have pulled the downloads as well.

**Comment by thabse** [comment]
Thanks for the update. Will you drop support for said versions or will you investigate further?

**Comment by aaronparker** [comment]
I'll try look for the older download but I'm not confident I can resolve this.

Do you specifically require those versions? there are other `2005` and `2008` release that are still available

**Comment by thabse** [comment]
To be honest, I'm not sure if other versions would work. (Old) C++ redistributables aren't my area of expertise.
Are the newer `2008` releases backwards compatible? Could I encounter any issues when installing the newest `2008` release without recompiling/adapting the software that uses it?

**Comment by aaronparker** [comment]
I can't say for certain, but those later `2008` releases were to address security issues, so it's likely the application will continue to work.

**Comment by aaronparker** [comment]
I've removed the unavailable VcRedists from 4.1 #123

**Comment by idris0001** [comment]
How do I download "Visual C++ V8.0"?

**Comment by warcommander2099** [comment]
Salam Alaikuom

C++ 2008 It is 9.0.30729.4148 Not 9.0.30729.6161 x86+64

Thx For ur Work :)
