### ISSUE TITLE
Intune Detection Rule not valid

### ISSUE THREAD

**Issue by ToolingModus** [aaronparker/vcredist#117]
It seems like the latest Visual C++ 2022 Redistributable installs two programs.
The current intune detection rule does not work.

![vcredist intune detection issue 1](https://user-images.githubusercontent.com/117843575/200881988-3b0692bc-e10b-4a50-adeb-6204ac88a678.png)

![vcredist intune detection issue 2](https://user-images.githubusercontent.com/117843575/200881984-1c5c3a6e-ba10-4ded-b9b6-3635f63bfc28.png)

![vcredist intune detection issue 3](https://user-images.githubusercontent.com/117843575/200881990-01f6e5be-afaa-4c9f-963f-24b365922162.png)

**Comment by aaronparker** [comment]
Each Redistributable has 3 entries in the Uninstall key - those two in the 64-bit key, but another in the 32-bit key. The 2022 Redistributables were updated last night, so there's likely a mismatch in the product GUID. I just need to merge the updated manifest in `development` into `main` for a module release

**Comment by ToolingModus** [comment]
Ah. Great to know that this is a quick fix.

I suppose it would be nicer if the product code could be dynamically determined. No idea if this is possible..

**Comment by aaronparker** [comment]
You could use a custom detection script in the Intune Win32 app. 

I've pushed a new version of the module with the updated manifest yesterday, so creating the app now will have the right details

**Comment by ToolingModus** [comment]
Solved with https://github.com/aaronparker/vcredist/commit/42dd636fc0b875aa3306d00b51d582d89d0a2f6c
