### ISSUE TITLE
install.ps1 script has syntax errors

### ISSUE THREAD

**Issue by stryder199** [aaronparker/vcredist#130]
# Expected Behavior

https://vcredist.com/install.ps1 installs latest vcredist packages

# Current Behavior

https://vcredist.com/install.ps1 fails with syntax errors

# Failure Information (for bugs)

```
Checking whether module is installed: VcRedist.
Installing module: VcRedist 4.1.480.
Saving VcRedists to path: C:\Users\markless\AppData\Local\Temp\VcRedist.
Downloading supported Microsoft Visual C++ Redistributables.
Save-VcRedist:
Line |
  57 |  $VcList = Get-VcList | Save-VcRedist -VcList -Path $Path
     |                                       ~~~~~~~
     | Missing an argument for parameter 'VcList'. Specify a parameter of type 'System.Management.Automation.PSObject' and try again.
Installing supported Microsoft Visual C++ Redistributables.
Install-VcRedist:
Line |
  60 |  $Redists = Install-VcRedist -VcList $VcList
     |                                      ~~~~~~~
     | Cannot validate argument on parameter 'VcList'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
Install complete.
Installed Visual C++ Redistributables:
```

**_If it is not a bug, please remove the rest of this template._**

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://vcredist.com/install.ps1'))

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* **VcRedist Version**: 4.1.480
* **PowerShell Version**: 7.2.9
* **Operating System**: Windows 11

**Comment by aaronparker** [comment]
I've updated the script to account for VcRedist 4.1 syntax changes, it should be pushed to the site in a few minutes
