### ISSUE TITLE
Re-add Proxy Server Support

### ISSUE THREAD

**Issue by bmitchell76** [aaronparker/vcredist#131]
Prior to v4.1 we could pass VcRedist -Proxy and -ProxyCredential parameters, these are gone with the latest version.  Can you bring them back?

**Comment by aaronparker** [comment]
Are you referring to `Save-VcRedist`? `-Proxy` and `-ProxyCredential` are still there. Could you demonstrate in example or screenshot etc. what's happening?

**Comment by bmitchell76** [comment]
🤦‍♂️, it’s there and working with Save-VcRedist—false alarm; nothing to see here.
