### ISSUE TITLE
Latest version number reported is inaccurate

### ISSUE THREAD

**Issue by JonathanPitre** [aaronparker/vcredist#134]
# Expected Behavior

Visual C++ 2015-2022 runtime latest version is **14.36.32532.0** but the following command report 14.34.31938.0 even though the setup installs the latest version (14.36.32532.0  currently).

` (Get-VcList | Where-Object { $_.Release -eq "2022" }).Version`

# Current Behavior

An older version is being reported, 14.34.31938.0 currently

![image](https://github.com/aaronparker/vcredist/assets/15003329/0ab0e002-39e9-4667-82d9-22c3249c0281)

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug by issuing the command using the `-Verbose` command.

`(Get-VcList -Verbose | Where-Object { $_.Release -eq "2022" }).Version`

```
Paste the verbose output from the command here
```

VERBOSE: Reading VcRedist manifest 'C:\Program Files\PowerShell\Modules\VcRedist\4.1.483\VisualCRedistributables.json'.
VERBOSE: Converting JSON.
VERBOSE: Object count is: 6.
![image](https://github.com/aaronparker/vcredist/assets/15003329/ab1b36dd-3c3d-4556-8bb2-972f5f889c3d)
**_If it is not a bug, please remove the rest of this template._**

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run (Get-VcList -Verbose | Where-Object { $_.Release -eq "2022" }).Version
The wrong version gets reported.
2. You can find the latest version here https://community.chocolatey.org/packages/vcredist140

**Comment by aaronparker** [comment]
Module updated. The module manifest is updated automatically, I just need to get it to post automatically to the PowerShell Gallery when there are updates
