### ISSUE TITLE
Import-VcConfigMgrApplication failing

### ISSUE THREAD

**Issue by Jorrdddyy** [aaronparker/vcredist#142]
# Expected Behavior

Import the saved list of VcRedist into ConfigManager. Using the below command:

$VcList = Get-VcList | Save-VcRedist -Path "C:\IT-Extras\VcRedist"
Import-VcConfigMgrApplication -VcList $VcList -CMPath "Z:\VcRedist" -SMSSiteCode PR1 

# Current Behavior

What is the current behavior?

New-Item : Invalid operation
At C:\Program Files\WindowsPowerShell\Modules\VcRedist\4.1.484\Public\Import-VcConfigMgrApplication.ps1:87 char:21
+ ...             New-Item -Path $DestCmFolder -ErrorAction "Continue" > $n ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (FQDNHere...ation\VcRedists:String) [New-Item], WqlQueryExcepti
   on
    + FullyQualifiedErrorId : Path,Microsoft.PowerShell.Commands.NewItemCommand

Cannot find an overload for "Contains" and the argument count: "1".
At C:\Program Files\WindowsPowerShell\Modules\VcRedist\4.1.484\Public\Import-VcConfigMgrApplication.ps1:125 char:29
+                         if ($PSBoundParameters.Contains($NoCopy)) {
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

WARNING: Failed to create application Visual C++ Redistributable for Visual Studio 2012 Update 4 x64. - This was the only one which imported.
New-CMApplication : An object with the specified name already exists.
At C:\Program Files\WindowsPowerShell\Modules\VcRedist\4.1.484\Public\Import-VcConfigMgrApplication.ps1:179 char:36
+                             $app = New-CMApplication @cmAppParams
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Confi....NewApplication:NewApplication) [New-CMApplication],
    ArgumentException
    + FullyQualifiedErrorId : ObjectNameAlreadyExists,Microsoft.ConfigurationManagement.PowerShell.Cmdlets.AppMan.NewA
   pplication

Please help provide information about the failure if this is a bug by issuing the command using the `-Verbose` command.

VERBOSE: Importing module: C:\Program Files (x86)\Microsoft Endpoint Manager\AdminConsole\bin\ConfigurationManager.psd1

VERBOSE: Performing the operation "Creating" on target "PR1:\Application\VcRedists".

VERBOSE: Creating: PR1:\Application\VcRedists.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

New-Item : Invalid operation

At C:\Program Files\WindowsPowerShell\Modules\VcRedist\4.1.484\Public\Import-VcConfigMgrApplication.ps1:87 char:21

+ ...             New-Item -Path $DestCmFolder -ErrorAction "Continue" > $n ...

+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : InvalidOperation: (**Hostname**.nrc.a...ation\VcRedists:String) [New-Item], WqlQueryExcepti

   on

    + FullyQualifiedErrorId : Path,Microsoft.PowerShell.Commands.NewItemCommand

 

VERBOSE: Importing VcRedist app: 'Visual C++ Redistributable 2012 x64 11.0.61030.0'

VERBOSE: Performing the operation "Import ConfigMgr app" on target "'Visual C++ Redistributable for Visual Studio 2012

Update 4' in Z:\VcRedist".

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Performing the operation "Creating ConfigMgr application" on target "Visual C++ Redistributable for Visual

Studio 2012 Update 4 x64".

Cannot find an overload for "Contains" and the argument count: "1".

At C:\Program Files\WindowsPowerShell\Modules\VcRedist\4.1.484\Public\Import-VcConfigMgrApplication.ps1:125 char:29

+                         if ($PSBoundParameters.Contains($NoCopy)) {

+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (:) [], MethodException

    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

 

VERBOSE: Setting location to: PR1:\Application\VcRedists

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists\FQDN.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 16777343 AND SearchFolder = 0 AND Name = 'FQDN'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 16777343 AND SearchFolder = 0 AND Name = 'FQDN'

VERBOSE: Finish: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 16777343 AND SearchFolder = 0 AND Name = 'FQDN'.

Processed 0 results in 00:00:00.

VERBOSE: Getting FolderType failed - Cannot find folder FQDN at level 3 of path

FQDN\Application\VcRedists\FQDN .

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Getting FolderType for path FQDN\Application.

VERBOSE: FolderType is Category for path FQDN\Application.

VERBOSE: Getting FolderType for path FQDN\Application\VcRedists.

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName =

'SMS_ApplicationLatest' AND ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ObjectContainerNode WHERE ObjectTypeName = 'SMS_ApplicationLatest' AND

ParentContainerNodeId = 0 AND SearchFolder = 0 AND Name = 'VcRedists'

VERBOSE: Item exists - Path FQDN\Application\VcRedists is a valid path.

VERBOSE: Checking for existing application called 'Visual C++ Redistributable 2012 x64 11.0.61030.0'

VERBOSE: Start: Execution of WQL query: SELECT * FROM SMS_ApplicationLatest WHERE LocalizedDisplayName = 'Visual C++

Redistributable 2012 x64 11.0.61030.0'

VERBOSE: Executing WQL query: SELECT * FROM SMS_ApplicationLatest WHERE LocalizedDisplayName = 'Visual C++

Redistributable 2012 x64 11.0.61030.0'

WARNING: Failed to create application Visual C++ Redistributable for Visual Studio 2012 Update 4 x64.

New-CMApplication : An object with the specified name already exists.

At C:\Program Files\WindowsPowerShell\Modules\VcRedist\4.1.484\Public\Import-VcConfigMgrApplication.ps1:179 char:36

+                             $app = New-CMApplication @cmAppParams

+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : InvalidArgument: (Microsoft.Confi....NewApplication:NewApplication) [New-CMApplication],

    ArgumentException

    + FullyQualifiedErrorId : ObjectNameAlreadyExists,Microsoft.ConfigurationManagement.PowerShell.Cmdlets.AppMan.NewA

   pplication

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Step 1:  Open Powershell as admin, Create a new PSDrive to map the location to prevent any permissions getting in the way.
Step 2: Run Command '$VcList = Get-VcList | Save-VcRedist -Path "C:\IT-Extras\VcRedist"
Import-VcConfigMgrApplication -VcList $VcList -CMPath "Z:\VcRedist" -SMSSiteCode PR1'

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

VcRedist Version: 4.1.484
PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Windows 11 Version 22H2 ( OS Build 22621.2283)

## Failure Logs
I've attached photos of the install Vcredist version on my machine. as well as showing they are actually creating.
Please include any relevant log snippets or files here.
![Appwiz_VcRedist](https://github.com/aaronparker/vcredist/assets/138868520/f4dd17a7-53c9-4712-875d-ff030a314091)
![FileExplorer_CreatedFolders](https://github.com/aaronparker/vcredist/assets/138868520/ea923140-e047-4232-a791-09464749c505)

![CM_Applications](https://github.com/aaronparker/vcredist/assets/138868520/5dd2c9be-0d64-470e-962e-8f1e9b2ef95a)

**Comment by aaronparker** [comment]
Fixed in `4.1.493`
