### ISSUE TITLE
Blank Dependency entry on Apps imported from Import-VcMdtApp

### ISSUE THREAD

**Issue by StevenNoel** [aaronparker/VcRedist#45]
# Expected Behavior
(notice no dependency line)
guid : {a3db9d4f-0ac7-40be-877b-445ca1d0b415}
Name : Microsoft Visual C++ 2008 Service Pack 1 Redistributable Package MFC Security Update x64

# Current Behavior

guid       : {5d126958-0b0b-4ca2-bb75-aaf024545e6e}
Name       : Microsoft Visual C++ Redistributable for Visual Studio 2019 x86
Dependency : 

# Failure Information (for bugs)

Looks like you are writing in your Import-VcMdtApplication function:
Dependency            = ""

Getting errors in my MDT deployment as it thinks there is suppose to be a dependency.  However the function is writing a blank Dependency, so it doesn't look like anything is there in the GUI.  However the MDT deployment final summary errors at the end with an ERROR GUI (blank)

FYI, the application does install fine.

```
Paste the verbose output from the command here
```

**_If it is not a bug, please remove the rest of this template._**

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1)$apps = [xml](get-content "E:\DeploymentShare\Control\Applications.xml")
$apps.applications.application | FL GUID,Name,Dependency

If you see 'Dependency: ' with nothing there, then that's the issue. 

## Context

I tested editing your function and just removed the 'Dependency' line and reimported the function, deleted the apps out of the GUI, readded the apps via Function, all is well.

Let me know if you need me to send a PR.

**Comment by aaronparker** [comment]
Fixed in commit aede38b50a379d6e608ff62859fcecef6291ac42
