### ISSUE TITLE
Problem with x64

### ISSUE THREAD

**Issue by Air-Git** [aaronparker/VcRedist#51]
This is a first rate utility, and I am grateful for your work to publish it.
I have a peculiar problem using it in a deployment in Intune. My script downloads all the versions and bitness (x86 and x64) but it installs only the x86. If I run the script again interactively, it installs all of them easily and quickly. This is on W10 1903.
The command to install is: `Install-VcRedist -Path C:\Windows\Temp\VcRedist -VcList (Get-VcList) -Silent | Out-File "C:\Windows\Temp\VcRedist_Install.log"`
Any ideas why, running as a Service Account, it would install only x86?
Any way to configure debug logging?

I am guessing I need to run the script with x64 PowerShell. Trying that now.

**Comment by Air-Git** [comment]
Yes, that works. I am executing the script inside a win32 app, and I need to run it explicitly with a 64-bit instance of PowerShell.
Thanks again for producing an excellent product.

**Comment by aaronparker** [comment]
The default process the Intune PowerShell scripts run under is 32-bit. There is now an option on PowerShell scripts in Intune to `Run script in 64 bit PowerShell Host`.  Enable that and see how you go.

**Comment by Air-Git** [comment]
I have put the script into a Win32 application, because I prefer to manage it that way. You can use exclusion assignments, which you can't do in Scripts. Also, you can easily change the detection to make sure that everything is installed. The Intune Management Extension installer is still a 32-bit application, so you need to specify PowerShell x64 explicitly in the Program Install command.
