### ISSUE TITLE
Problem with Get-VcList Pipeline

### ISSUE THREAD

**Issue by Air-Git** [aaronparker/VcRedist#53]
Excellent product, thanks.
For some reason the pipeline Get-VcList | Save-VcRedist has stopped working. However, it works it you do: $VcList = Get-VcList; Save-VcRedist -VcList $VcList

**Comment by aaronparker** [comment]
The `-Path` parameter is empty by default. Adding `-Path .\` for example would fix this.

I’ll update so that it defaults to the current directory by default.

**Comment by Air-Git** [comment]
Sorry, I was being brief. 
The full command was: `Get-VcList | Save-VcRedist -Path C:\Windows\Temp\VcRedist -ForceWebRequest`. This has been working fine until a short while (days?) ago. Today in testing I found that this line now does nothing. I change it to: `$VcList = Get-VcList; Save-VcRedist -VcList $VcList -Path C:\Windows\Temp\VcRedist -ForceWebRequest` and it works as before.  As it happens, I also found that the next line, `Install-VcRedist etc. etc.` was kicking off before all the downloads were done, so i changed the whole thing to use `Start-Job; Wait-Job` and it is all working perfectly again.

**Comment by aaronparker** [comment]
I’m not seeing the second behaviour. I’ve updated a development version. Could you download the development branch from the repository and test?

**Comment by Air-Git** [comment]
Yes, tested and working. 
`$VcList = Get-VcList # gets the list`
`Save-VcRedist -VcList $VcList -Path C:\Windows\Temp\VcRedist -ForceWebRequest # downloads the executables, really fast`
`Install-VcRedist -Path C:\Windows\Temp\VcRedist -VcList $VcList -Silent # waits for the downloads to complete, then install.`

**Comment by Air-Git** [comment]
I also tried to reproduce the second behaviour with the master version, but it worked as expected this time, so I don't know what happened when I was trying it yesterday. Maybe some delay in responding to the web request? I know in the past it sometimes took two passes to get all the versions installed, so maybe that was the same issue. Anyway, it works like a charm now, thanks!

**Comment by aaronparker** [comment]
Fixed in #54 and commit b60c22e8a8b2d26079ef667d906f06167bdcbe39
