### ISSUE TITLE
Import-VcConfigMgrApplication Robocopy Error

### ISSUE THREAD

**Issue by mikeh36** [aaronparker/VcRedist#63]
# Expected Behavior
Copy the folders and files from the source to the network share

# Current Behavior

Files are copied as expected but an exception is being thrown that the copy failed

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug by issuing the command using the `-Verbose` command.

```
VERBOSE: Performing the operation "Copy" on target "C:\Temp\VCRedist to \\<networkpath>\Microsoft\Visual_CPlus_Redistributables_2020".


WARNING: Import-VcConfigMgrApplication: Failed to copy Redistributables from [C:\Temp\VCRedist] to [\\<networkpath>\Microsoft\Visual_CPlus_Redistributables_2020].
An object at the specified path C:\Users\OPE0F6~1.MIK does not exist.
At C:\Program Files\WindowsPowerShell\Modules\VcRedist\2.0.203\Public\Import-VcConfigMgrApplication.ps1:111 char:21
+                     Throw $_.Exception.Message
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (An object at th...does not exist.:String) [], RuntimeException
    + FullyQualifiedErrorId : An object at the specified path C:\Users\OPE0F6~1.MIK does not exist.
```

**_If it is not a bug, please remove the rest of this template._**

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.Import-VcConfigMgrApplication -VcList $VcList -Path "C:\Temp\VCRedist" -CMPath "\\<networkpath>\Microsoft\Visual_CPlus_Redistributables_2020" -SMSSiteCode N01 -Silent

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* **VcRedist Version**: 2.0.203
* **PowerShell Version**: 5.1
* **Operating System**: Server 2019 

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by KristoferOlafsson** [comment]
Same issue 
VcRedist Version: 2.0.209 
Powershell Version : 5.1.14409.1018
Windows 2012R2

PS C:\Temp\VcRedist> Install-Module VcRedist
Import-Module VcRedist
$VcList = Get-VcList
Get-VcRedist -VcList $VcList -Path "C:\Temp\VcRedist"
Import-VcConfigMgrApplication -VcList $VcList -Path "C:\Temp\VcRedist" -CMPath "\\server\Sources\VcRedist" -SMSSiteCode LAB -Verbose


Name          : Visual C++ 2008 Service Pack 1 Redistributable Package MFC Security Update
ProductCode   : {5FCE6D76-F5DC-37AB-B2B8-22AB8CEDB1D4}
Version       : 9.0.30729.6161
URL           : https://www.microsoft.com/en-us/download/details.aspx?id=26368
Download      : https://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x64.exe
Release       : 2008
Architecture  : x64
ShortName     : SP1MFC
Install       : /Q
SilentInstall : /Q

Name          : Visual C++ 2008 Service Pack 1 Redistributable Package MFC Security Update
ProductCode   : {9BE518E6-ECC6-35A9-88E4-87755C07200F}
Version       : 9.0.30729.6161
URL           : https://www.microsoft.com/en-us/download/details.aspx?id=26368
Download      : https://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x86.exe
Release       : 2008
Architecture  : x86
ShortName     : SP1MFC
Install       : /Q
SilentInstall : /Q

VERBOSE: Import-VcConfigMgrApplication: Set location to [C:\Temp\VcRedist].
VERBOSE: Performing the operation "Copy" on target "C:\Temp\VcRedist to \\server\Sources\VcRedist".
WARNING: Import-VcConfigMgrApplication: Failed to copy Redistributables from [C:\Temp\VcRedist] to [\\server\Sources\VcRedist].
At C:\Program Files\WindowsPowerShell\Modules\VcRedist\2.0.209\Public\Import-VcConfigMgrApplication.ps1:111 char:21
+                     Throw $_.Exception.Message
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:String) [], RuntimeException
    + FullyQualifiedErrorId : 
 

PS C:\Temp\VcRedist>

**Comment by aaronparker** [comment]
Is `\server\Sources\VcRedist` an artefact of posting here and you're not actually missing a `\` in the path `\\server\Source\VcRedist`?

I notice my code isn't accounting for spaces in the source and target paths as well. This line would fail is there's a space in these paths, so I need to update with a fix:

`ArgumentList = "*.exe $validPath $CMPath /S /XJ /R:1 /W:1 /NP /NJH /NJS /NFL /NDL"`
