### ISSUE TITLE
Uninstall-VcRedist triggers reboot

### ISSUE THREAD

**Issue by DailenG** [aaronparker/VcRedist#64]
# Expected Behavior

Uninstall-VcRedist should run commands to quietly uninstall installed redists without interrupting the user. 

# Current Behavior

Uninstall-VcRedist appears to run uninstalls quietly mandatory reboots appear to be enforced. when testing the command it prompted me if I was sure i wanted to uninstall so i added "-confirm:$false" in an attempt to make the command completely run silent.

## Steps to Reproduce

1. uninstall-vcredist -Confirm:$false

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* **VcRedist Version**: 2.0.204
* **PowerShell Version**: 5.1.20161.1000
* **Operating System**: 20161.1000 release 2004

**Comment by DailenG** [comment]
I didn't mention it in the issue text but if a reboot is necessary, it should just flag the system (if vc redistributables didn't already) and notify the user at the end maybe with an option to reboot once it's finished.

**Comment by aaronparker** [comment]
Which VcRedist uninstall caused a reboot? VcRedists 2010 and below don't support a no reboot switch.

I can add the `/noreboot` switch to the uninstall parameters for those VcRedists that support it to suppress a reboot.
